### ISSUE TITLE
[Question] Does it requires G29 with specific bed leveling compilation option or is G33 good enough?

### ISSUE THREAD

**Issue by mgcrea** [Fabi0San/OctoPrint-LSqDeltaCalibration#17]
I'm currently printing with an FLsun Q5 calibrated solely with G33, so my understanding is that I'm not currently leveraging any bed mesh levelling calibration (G33 does probe the bed but only to find delta geometry if i understand correctly).

My question is can I directly use this plugin or should I first start with a G29 bed levelling, and if so which option do you recommend in Marlin's firmware? `AUTO_BED_LEVELING_UBL` or `AUTO_BED_LEVELING_BILINEAR`, currently I don't have any option enabled.

Thanks!

---

Just tried probing and while it does properly get a good first probe point it does fail quickly after:

```
Recv: Bed X: 5.93 Y: -19.10 Z: 0.19
Recv: X:5.93 Y:-19.10 Z:20.09 E:0.00 Count A:16679 B:17133 C:15589
Recv: ok
Send: M118 DONE_4
Recv: DONE_4
Recv: ok
Send: G0 Z20
Recv: ok
Send: G0 X24.24409 Y-3.49630
Recv: ok
Send: G30 E0
[...]
Recv: Bed X: 24.24 Y: -3.50 Z: -1.04
Recv: X:24.24 Y:-3.50 Z:18.86 E:0.00 Count A:15431 B:17355 C:16189
Recv: ok
Send: M118 DONE_5
Recv: DONE_5
Recv: ok
Send: G0 Z20
Recv: ok
Send: G0 X19.57089 Y20.42010
Recv: ok
Send: G30 E0
[...]
Recv: Error:Probing Failed
Changing monitoring state from "Operational" to "Error: Probing Failed"
Send: M112
Send: N55315 M112*38
Send: N55316 M104 T0 S0*37
Send: N55317 M140 S0*96
Changing monitoring state from "Error: Probing Failed" to "Offline (Error: Probing Failed)"
Connection closed, closing down monitor
```

**Comment by Fabi0San** [comment]
I need to see the long lines immediately before the error.
