### ISSUE TITLE
Rod Length

### ISSUE THREAD

**Issue by azreal1983** [Fabi0San/OctoPrint-LSqDeltaCalibration#19]
I have run 9 trials.

The first 7 got down to 0.070 RMS. I only changed Tower Offset, Endstop Offset and Delta Radius.

Now for 8 onwards I have unticked Rod length. I know my rod length is 272mm give or take a few microns. (as build with a jig)

however, the results so far for Rod Length 281.1472mm - which I know even using a ruler are way off.

If I carry on probing, will it eventually converge near 272mm?

**Comment by Fabi0San** [comment]
This indicates a problem with your belt tooth distance due to over/under tension, manufacturing errors or thermal expansion.
Tune your belts first using a machinist dial.
