### ISSUE TITLE
DuCalibrator hangs during 'Fetch Geometry'

### ISSUE THREAD

**Issue by wildeep** [Fabi0San/OctoPrint-LSqDeltaCalibration#20]
Observed: On my MP Mini Delta, after entering 100 as my probing radius, and clicking 'Fetch Geometry', the UI shows the spinning gear, but the printer does nothing, and I let the Fetch run for 5 minutes.

Not sure if I'm trying to use this tool on an incompatible printer (I have no idea if it's using Marlin firmware) or if there's a setting I can adjust.

**Comment by Fabi0San** [comment]
you are likely not using marlin fw, or an old version, a dump of the terminal messages would help.
